#!/usr/bin/env bash

# this script only works for the p1 assignment
# a different script will be posted for the other assignments

# this script assumes that the tests (t001, t001.out, t001.err, t002, etc) live
# in the directory ./tests (where . is the directory containing the executable)
# you can change this so that the tests are in the current directory by
# changing the following line to:  test_dir=.
test_dir=tests

# this script puts the results in the directory ./results
# you can modify this script so results are put in the current directory by
# changing the following line to:  result_dir=.
result_dir=results

passed=0
failed=0


# create the results directory if it does not exist 
#  (mkdir does nothing if it already exists.  the error will be ignored)
mkdir $result_dir 2>/dev/null

for test_file in $test_dir/t[0-9][0-9][0-9].in; do
    test_name=${test_file##*/}
    test_name=${test_name%%\.in}

    ./parser $test_file > $result_dir/$test_name.myout 2> $result_dir/$test_name.myerr

    if diff $result_dir/$test_name.myout $test_dir/$test_name.out >& /dev/null &&
       diff $result_dir/$test_name.myerr $test_dir/$test_name.err >& /dev/null
    then 
        (( passed++ ))
    echo "Passed $test_name"
    elif diff $result_dir/$test_name.myout $test_dir/$test_name.out >& /dev/null 
    then
        echo "Failed $test_name: stderr incorrect"
        (( failed++ ))
    elif diff $result_dir/$test_name.myerr $test_dir/$test_name.err >& /dev/null
    then
        echo "Failed $test_name: stdout incorrect"
        (( failed++ ))
    else
        echo "Failed $test_name: stdout & stderr incorrect"
        (( failed++ ))
    fi        

done


total=$passed
(( total += failed ))
echo "Passed $passed out of $total tests."
echo "Failed $failed out of $total tests."
